### ISSUE TITLE
First line is always treated as code block

### ISSUE THREAD

**Issue by panw** [perak/markdown#5]
I am running into unexpected behavior where the first line of markdown is always treated as a code block. Please see my image below. I'm using the latest version of this package with Meteor 1.2.0.1. Here is code I have in my template
```
{{#markdown}}
  {{markdownCodeFromHelper}}
{{/markdown}}
```
The editor on the left is CodeMirror with Markdown mode. I don't think it would be CodeMirror because I have tried hard coding the values in the template and the same behavior is occuring.

Any thoughts? Thanks

<img width="1181" alt="screen shot 2015-10-04 at 11 49 01 pm" src="https://cloud.githubusercontent.com/assets/857822/10272756/9e1dcbac-6af2-11e5-8929-bafd580df22e.png">

**Comment by perak** [comment]
@panw this is because indentation Your {{markdownCodeFromHelper}} starts with spaces (it's indented) and that is markdown syntax for code block. Yust remove leading spaces and it wil be OK

**Comment by panw** [comment]
Good call. Thanks
