### ISSUE TITLE
Security?

### ISSUE THREAD

**Issue by Pushplaybang** [perak/markdown#6]
are there any inherent security risks with this plugin?

**Comment by jhuenges** [comment]
What risks would you suspect?

**Comment by Pushplaybang** [comment]
Other than the obvious, placing a misleading link, or image into the markdown, is the input sanitized at all?  Is this opening up the possibility for XSS?  or has that been considered?

Is there anything I, or others, should do additionally (specific to using this package) when using this in an application to protect ourselves and our users?

**Comment by perak** [comment]
@Pushplaybang user can insert anything into markdown, html content including links - markdown is not filtered at all. You can do it before storing data into database (for example, replacing `<script>` & `</script>` tags with something else or similar).

**Comment by perak** [comment]
(or, maybe easiest way it to replace `<` with `&lt;` and `>` with `&gt;`)

**Comment by Pushplaybang** [comment]
ok thanks,   I've changed to using [chuangbo:marked](https://atmospherejs.com/chuangbo/marked) as it seems to have a few more options and buit in sanitization.  

thanks.
